---
- hosts: do
  tasks:
    - name: move old nginx config
      command: /bin/mv /etc/nginx /etc/nginx-old
    - name: copy new nginx config
      copy: src=./dist/ dest=/etc/nginx owner=www-data group=www-data
      notify:
      - restart nginx
    - name: ensure nginx is running
      service: name=nginx state=started enabled=yes
  handlers:
    - name: restart nginx
      command: /usr/sbin/nginx -s restart