---
- hosts: do
  tasks:
    - name: remove old nginx config
      command: /bin/rm -r /etc/nginx
    - name: copy new nginx config
      copy: src=./dist/ dest=/etc/nginx owner=www-data group=www-data backup=yes
      notify:
      - restart nginx
    - name: ensure nginx is running
      service: name=nginx state=started enabled=yes
  handlers:
    - name: restart nginx
      command: /usr/sbin/nginx -s reload
